version: '3'
services:
  # use logging.critical() instead of print()
  # ports
  # environment variables
  # shared volumes

  tweets:
    # prints a random fruit every 10 seconds
    build: tweets/
    volumes:
       - ./tweets/:/app
    depends_on:
    - mongodb

  etl:
    build: etl/
    volumes:
       - ./etl/:/app
    depends_on:
    - mongodb
    - postgresdb
    restart: "always"

  slack:
    build: slack/
    volumes:
      - ./slack/:/app
    depends_on:
      - postgresdb

  #spices:
    # prints a random spice every 10 seconds
  #  build: spices/
  #  volumes:
  #  - ./spices/:/app
    #command:
    #- ["python", "random_spice.py"]

  postgresdb:
    image: postgres
    #port mapping LOCAL:CONTAINER
    ports:
    - 5555:5432
    environment:
    - POSTGRES_PASSWORD=1234

  mongodb:
    image: mongo
    ports:
    - 27018:27017
    # psql -h 0.0.0.0 -p 5555 -U postgres postgres
